channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - bokeh>=2.4.2,<3
  - cachey=0.2.1
  - cytoolz>=0.12
  - dask=2023.10.1
  - distributed=2023.10.1
  - h5py
  - jq=1.6
  - jupyter-server-proxy
  - lz4>=4.3.2
  - msgpack-python
  - nomkl=3.0
  - numpy>=1.26.0
  - pandas=1.5.1
  - psutil>=5.7.2
  - python-blosc=1.10.6
  - s3fs>=2021.9.0
  - scipy>=1.9.1
  - streamz=0.6.3
  - tblib>=1.6.0
  - zarr=2.16.1
  - pip:
    - cloudpickle==3.0.0
