FROM python:3

LABEL base_image="python:3"
LABEL version="1"
LABEL software="falcon-ms"
LABEL software.version="0.1.3"
LABEL about.summary="Large-scale tandem mass spectrum clustering using fast nearest neighbor searching"
LABEL about.home="https://github.com/bittremieux/falcon"
LABEL about.license="BSD-3-Clause"
LABEL about.license_file="https://github.com/bittremieux/falcon/blob/main/LICENSE.txt"
LABEL about.documentation="https://github.com/bittremieux/falcon/blob/main/README.md"
LABEL maintainer ="olivier.sallou@irisa.fr"

RUN pip install falcon-ms==v0.1.3
