################## BASE IMAGE ######################
FROM biocontainers/biocontainers:v1.0.0_cv4

################## METADATA ######################
LABEL base_image="biocontainers:v1.0.0_cv4"
LABEL version="2"
LABEL software="vcftools"
LABEL software.version="0.1.15"
LABEL about.summary="A set of tools written in Perl and C++ for working with VCF files, such as those generated by the 1000 Genomes Project"
LABEL about.home="https://github.com/vcftools/vcftools|https://vcftools.github.io/index.html"
LABEL about.documentation="https://github.com/vcftools/vcftools|https://vcftools.github.io/index.html"
LABEL about.license_file="https://github.com/vcftools/vcftools|https://vcftools.github.io/index.html"
LABEL about.license="SPDX:LGPL-3.0-only"
LABEL about.tags="Genomics"
LABEL extra.identifiers.biotools="vcftools"

################## MAINTAINER ######################
MAINTAINER Saulo Alves Aflitos <sauloal@gmail.com>

USER root

ENV ZIP=vcftools-0.1.15.tar.gz
ENV URL=https://github.com/vcftools/vcftools/releases/download/v0.1.15/
ENV FOLDER=vcftools-0.1.15
ENV DST=/tmp

RUN apt-get update && apt-get install -y tabix

RUN wget $URL/$ZIP -O $DST/$ZIP && \
  tar xvf $DST/$ZIP -C $DST && \
  rm $DST/$ZIP && \
  cd $DST/$FOLDER && \
  ./configure && \
  make && \
  make install && \
  cd / && \
  rm -rf $DST/$FOLDER

USER biodocker

RUN wget https://github.com/vcftools/vcftools/blob/master/examples/floats.vcf && \
    vcftools --vcf floats.vcf && rm floats.vcf

WORKDIR /data/
