# Calls biocontainer-ci repo / bioconda-backup script
# on self hosted node

name: Bioconda and docker backups

on:
  schedule:
  - cron: "0 23 * * * "

jobs:

  build:
    timeout-minutes: 1440 
    runs-on: self-hosted
    steps:
    - name: Backup bioconda and docker containers to local and aws registries
      run: |
        cd /home/debian/sync && node index.js --backup --aws --conda --updated
        cd /home/debian/sync && node index.js --aws --docker --updated
